import { readFileSync } from "node:fs";
import { join } from "node:path";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

/** Absolute path to the committed binary fixtures (generated by the .py script). */
export const DATA_DIR = join(__dirname, "..", "test-data");

export function dataFile(name: string): string {
  return join(DATA_DIR, name);
}

export function dataBytes(name: string): Buffer {
  return readFileSync(dataFile(name));
}

/** A Playwright setInputFiles payload built from an in-memory buffer. */
export interface FilePayload {
  name: string;
  mimeType: string;
  buffer: Buffer;
}

export function payload(name: string, mimeType: string, buffer: Buffer): FilePayload {
  return { name, mimeType, buffer };
}

/** Build a deterministic multi-page PDF with selectable text on every page. */
export async function makePdf(pages: number, label = "Acme Widgets audit"): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  for (let i = 0; i < pages; i++) {
    const page = doc.addPage([595, 842]);
    page.drawText(`${label} — page ${i + 1}`, { x: 72, y: 760, size: 24, font, color: rgb(0.1, 0.1, 0.2) });
    page.drawText(`Deterministic fixture content, page index ${i}.`, {
      x: 72,
      y: 720,
      size: 12,
      font,
      color: rgb(0.4, 0.4, 0.5),
    });
  }
  return Buffer.from(await doc.save());
}

/** A tiny valid 4x4 red PNG (kept inline so text specs need no disk read). */
export const TINY_PNG = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAYAAACp8Z5+AAAAEUlEQVR4nGNk+P+/noEMwDgKAGBJAwQ5+v7yAAAAAElFTkSuQmCC",
  "base64",
);

/** Named binary fixtures on disk, with their true MIME types. */
export const FILES = {
  singlePdf: () => payload("single.pdf", "application/pdf", dataBytes("single.pdf")),
  multiPdf: () => payload("multipage.pdf", "application/pdf", dataBytes("multipage.pdf")),
  tablePdf: () => payload("table.pdf", "application/pdf", dataBytes("table.pdf")),
  scannedPdf: () => payload("scanned.pdf", "application/pdf", dataBytes("scanned.pdf")),
  unicodePdf: () => payload("unicode.pdf", "application/pdf", dataBytes("unicode.pdf")),
  lockedPdf: () => payload("locked.pdf", "application/pdf", dataBytes("locked.pdf")),
  corruptedPdf: () => payload("corrupted.pdf", "application/pdf", dataBytes("corrupted.pdf")),
  emptyPdf: () => payload("empty.pdf", "application/pdf", Buffer.alloc(0)),
  jpg: () => payload("photo.jpg", "image/jpeg", dataBytes("photo.jpg")),
  png: () => payload("photo.png", "image/png", dataBytes("photo.png")),
  webp: () => payload("photo.webp", "image/webp", dataBytes("photo.webp")),
  transparentPng: () => payload("transparent.png", "image/png", dataBytes("transparent.png")),
  widePng: () => payload("wide.png", "image/png", dataBytes("wide.png")),
  tallPng: () => payload("tall.png", "image/png", dataBytes("tall.png")),
  tinyPng: () => payload("tiny.png", "image/png", dataBytes("tiny.png")),
  corruptedPng: () => payload("corrupted.png", "image/png", dataBytes("corrupted.png")),
  heic: () => payload("photo.heic", "image/heic", dataBytes("photo.heic")),
  xlsx: () =>
    payload(
      "book.xlsx",
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      dataBytes("book.xlsx"),
    ),
  docx: () =>
    payload(
      "doc.docx",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      dataBytes("doc.docx"),
    ),
  /** An executable's bytes wearing a .pdf name — spoofed extension attack. */
  spoofedPdf: () => payload("malware.pdf", "application/pdf", Buffer.from("MZ\x90\x00fake-exe-bytes")),
  /** A real PNG carrying a .jpg name — renamed-extension case. */
  renamedPng: () => payload("actually.jpg", "image/jpeg", dataBytes("photo.png")),
  /** Filename edge cases, all carrying valid single-page PDF bytes. */
  unicodeNamePdf: async () => payload("রিপোর্ট-café-🎉.pdf", "application/pdf", await makePdf(1)),
  spacesNamePdf: async () => payload("my important report (final).pdf", "application/pdf", await makePdf(1)),
  longNamePdf: async () => payload(`${"a".repeat(200)}.pdf`, "application/pdf", await makePdf(1)),
} as const;

/** Deterministic text payloads for developer / text / data tools. */
export const TEXT = {
  validJson: '{"name":"Acme Widgets","tools":81,"nested":{"a":[1,2,3]}}',
  malformedJson: '{"name":"Acme Widgets", "tools": 81,}',
  deeplyNestedJson: JSON.stringify(nest(40)),
  validYaml: "name: Acme Widgets\ntools: 81\nlist:\n  - a\n  - b\n",
  malformedYaml: "name: : : bad\n  - unbalanced\n:::",
  validCsv: "name,tools\nAcme Widgets,81\n\"Quoted, comma\",7",
  malformedCsv: 'a,b,c\n"unterminated,quote,here',
  markdown: "# Title\n\nSome **bold** and a [link](https://example.com).\n\n- one\n- two",
  htmlDangerous: '<img src=x onerror="alert(1)"><script>alert(2)</script># Heading',
  base64Valid: "QWNtZSBXaWRnZXRz", // "Acme Widgets"
  base64Invalid: "!!!not-base64!!!",
  jwtValid:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
  jwtInvalid: "not.a.jwt",
  unicode: "café résumé naïve — 日本語 — Bangla রিপোর্ট — emoji 🎉🔥",
  bangla: "রিপোর্ট তৈরি হয়েছে। ধন্যবাদ।",
  emoji: "🎉🔥💯👍🚀".repeat(10),
  longText: "lorem ipsum ".repeat(5000),
  empty: "",
  whitespace: "   \n\t  ",
  sql: "select a,b from t where x=1 and y=2 order by a",
  regexPattern: "\\b(\\w+)@(\\w+)\\.com\\b",
  regexText: "reach me at alice@example.com or bob@test.com",
} as const;

function nest(depth: number): unknown {
  let o: unknown = { leaf: true };
  for (let i = 0; i < depth; i++) o = { [`level${i}`]: o };
  return o;
}
