export const siteConfig = {
  name: "PDF Studio",
  shortName: "PDFStudio",
  description:
    "Free online PDF tools — compress, merge, convert PDF to Word/Excel/JPG, OCR in 100+ languages, lock, unlock, and sign. No signup, no watermark, files auto-delete in 1 hour.",
  tagline: "All-in-one PDF toolkit. Free, fast, watermark-free.",
  url: (process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000").replace(/\/+$/, ""),
  locale: "en_US",
  twitter: "@pdfstudio",
  themeColor: "#6366f1",
  keywords: [
    "compress pdf online free",
    "merge pdf online",
    "pdf compressor",
    "reduce pdf size",
    "pdf to jpg converter",
    "pdf to png",
    "lock pdf online",
    "unlock pdf",
    "remove pdf password",
    "extract text from scanned pdf",
    "pdf to excel",
    "pdf to word",
    "word to pdf",
    "jpg to pdf",
    "sign pdf online",
    "free pdf tools",
    "online pdf editor",
    "pdf compress bd",
    "nid combine pdf",
    "bangla ocr",
    "passport photo pdf",
    "100kb pdf compressor",
  ],
  plausibleDomain: process.env.NEXT_PUBLIC_PLAUSIBLE_DOMAIN || "",
} as const;
