export const siteConfig = {
  name: "PDF Studio",
  shortName: "PDFStudio",
  description:
    "Free online PDF tools, merge, compress, split, lock, OCR, NID combine, bank statement to Excel. Built for Bangladesh.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
  locale: "en_US",
  alternateLocale: "bn_BD",
  twitter: "@pdfstudio",
  themeColor: "#7c3aed",
  keywords: [
    "PDF merge",
    "PDF compress",
    "PDF tools",
    "PDF to JPG",
    "PDF lock",
    "PDF unlock",
    "NID combine",
    "Bangla OCR",
    "bank statement to Excel",
    "passport photo PDF",
    "merge PDF online",
    "compress PDF online",
    "free PDF tools Bangladesh",
    "পিডিএফ মার্জ",
    "পিডিএফ কম্প্রেস",
    "এনআইডি কম্বাইন",
    "বাংলা ওসিআর",
  ],
  plausibleDomain: process.env.NEXT_PUBLIC_PLAUSIBLE_DOMAIN || "",
} as const;
